MvcWeb/MvcWeb/Models/Entity/Heading.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcWeb.Models.Entity
{
    public class Heading
    {
        [Key]
        public int HeadingId { get; set; }

        [StringLength(120)]
        public string Name { get; set; }

        public bool IsActive { get; set; }

        public ICollection<Content> Contents { get; set; }
    }
}

MvcWeb/MvcWeb/Controllers/HeadingController.cs
using FluentValidation.Results;
using MvcWeb.Helper;
using MvcWeb.Models.Entity;
using MvcWeb.Models.Validations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using static MvcWeb.Helper.ImageUpload;

namespace MvcWeb.Controllers
{
    public class HeadingController : Controller
    {
        Context db = new Context();

        // GET: Heading
        public ActionResult Index()
        {
            var list = db.Headings.ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddHeading(Heading heading)
        {
            HeadingValidator headingValidator = new HeadingValidator();
            ValidationResult result = headingValidator.Validate(heading);

            if (result.IsValid)
            {

                db.Headings.Add(heading);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            var value = db.Headings.Find(id);
            return View("EditHeading", value);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditHeading(Heading heading)
        {
            HeadingValidator headingValidator = new HeadingValidator();
            ValidationResult result = headingValidator.Validate(heading);

            var value = db.Headings.Find(heading.HeadingId);

            if (result.IsValid)
            {
                value.Name = heading.Name;
                value.IsActive = true;
                db.SaveChanges();
                TempData["AlertMessage"] = "Başlık Başarıyla Güncellendi";
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult IsActiveChangingHeading(int id)
        {
            var deletevalue = db.Headings.Find(id);
            if (deletevalue.IsActive == true)
            {
                deletevalue.IsActive = false;
            }
            else
            {
                deletevalue.IsActive = true;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteHeading(int id)
        {
            var deletevalue = db.Headings.Find(id);
            //db.Headings.Remove(deletevalue);
            deletevalue.IsActive = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcWeb/MvcWeb/Views/Heading/AddHeading.cshtml
@model MvcWeb.Models.Entity.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Başlık</span> - Yönetimi</h4>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/Dashboard"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="/Heading/Index">Başlık Listesi</a></li>
            <li class="active">Başlık Ekle</li>
        </ul>
    </div>
</div>


<!-- Content area -->
<div class="content">
    <!-- /page header -->
    <div class="panel panel-flat">
        <div class="panel-body">
            @using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="text-semibold">
                            <legend><i class="icon-reading position-left"></i> İçerik Başlık Bilgileri</legend>
                            <div class="form-group">
                                <label>Başlık Adı</label>
                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Kaydet <i class="icon-arrow-right14 position-right"></i></button>
                </div>
            }
        </div>
    </div>
</div>

MvcWeb/MvcWeb/Views/Heading/EditHeading.cshtml
@model MvcWeb.Models.Entity.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Başlık</span> - Yönetimi</h4>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/Dashboard"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="/Heading/Index">Başlık Listesi</a></li>
            <li><a href="/Heading/AddHeading">Başlık Ekle</a></li>
            <li class="active">Başlık Güncelle</li>
        </ul>
    </div>
</div>


<!-- Content area -->
<div class="content">
    <!-- /page header -->
    <div class="panel panel-flat">
        <div class="panel-body">
            @using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="text-semibold">
                            <legend><i class="icon-reading position-left"></i> İçerik Başlık Bilgileri</legend>
                            <div class="form-group">
                                <label>Başlık Adı</label>
                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Güncelle <i class="icon-arrow-right14 position-right"></i></button>
                </div>
            }
        </div>
    </div>
</div>

MvcWeb/MvcWeb/Views/Heading/Index.cshtml
@using MvcWeb.Models.Entity
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Başlıklar</span></h4>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/Dashboard"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="/Heading/AddHeading">Yeni Başlık Ekle</a></li>
            <li class="active">Başlık Listesi</li>
        </ul>
    </div>
</div>
<!-- /page header -->
<!-- Content area -->
<div class="content">
    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Başlık</th>
                    <th scope="col">Durum</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @{ int siraNo = 0;}
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@{siraNo++;} @siraNo</th>
                        <td>@item.Name</td>
                        <td>
                            @if (item.IsActive == true)
                            {
                                <a href="/Heading/IsActiveChangingHeading/@item.HeadingId">
                                    <span class="bg-success text-highlight">Aktif</span>
                                </a>

                            }
                            else
                            {
                                <a href="/Heading/IsActiveChangingHeading/@item.HeadingId">
                                    <span class="bg-danger text-highlight">Pasif</span>
                                </a>
                            }
                        </td>
                        <td>
                            <a href="/Heading/EditHeading/@item.HeadingId" class="btn btn-warning">Güncelle</a>
                            <a href="/Heading/DeleteHeading/@item.HeadingId" class="btn btn-danger">Sil</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>
<!-- /content area -->