MvcWeb/MvcWeb/Models/Entity/Content.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcWeb.Models.Entity
{
    public class Content
    {
        [Key]
        public int ContentId { get; set; }

        [StringLength(100)]
        [Required(ErrorMessage = "Başlık Giriniz")]
        public string Name { get; set; }

        [AllowHtml] 
        [Required(ErrorMessage = "Description Giriniz")]
        public string Description { get; set; }

        [StringLength(150)]
        public string Picture { get; set; }

        public bool IsActive { get; set; }

        public int HeadingId { get; set; }
        public virtual Heading Heading { get; set; }
    }
}

MvcWeb/MvcWeb/Controllers/ContentController.cs
using FluentValidation.Results;
using MvcWeb.Helper;
using MvcWeb.Models.Entity;
using MvcWeb.Models.Validations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static MvcWeb.Helper.ImageUpload;

namespace MvcWeb.Controllers
{
    public class ContentController : Controller
    {
        Context db = new Context();
        // GET: Content

        public ActionResult Index()
        {
            var list = db.Contents.Where(x => x.IsActive == true).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult AddContent()
        {
            List<SelectListItem> listvalue = (from x in db.Headings.Where(x => x.IsActive == true)
                                              select new SelectListItem
                                              {
                                                  Text = x.Name,
                                                  Value = x.HeadingId.ToString()
                                              }).ToList();

            ViewBag.value = listvalue;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddContent(Content content)
        {
            ContentValidator contentValidator = new ContentValidator();
            ValidationResult result = contentValidator.Validate(content);

            if (result.IsValid)
            {
                foreach (string item in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[item] as HttpPostedFileBase;
                    if (file.ContentLength == 0)
                        continue;
                    if (file.ContentLength > 0)
                    {
                        ImageUpload imageUpload = new ImageUpload { Width = 500 };
                        ImageResult imageResult = imageUpload.RenameUploadFile(file);

                        if (imageResult.Success)
                        {
                            content.Picture = imageResult.ImageName;
                        }
                        else
                        {
                            ViewBag.Error = imageResult.ErrorMessage;
                        }
                    }
                }

                db.Contents.Add(content);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditContent(int id)
        {
            List<SelectListItem> listvalue = (from x in db.Headings.Where(x => x.IsActive == true)
                                              select new SelectListItem
                                              {
                                                  Text = x.Name,
                                                  Value = x.HeadingId.ToString()
                                              }).ToList();

            ViewBag.value = listvalue;

            var icerikbul = db.Contents.Find(id);
            return View("EditContent", icerikbul);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditContent(Content p)
        {
            ContentValidator contentValidator = new ContentValidator();
            ValidationResult result = contentValidator.Validate(p);

            var value = db.Contents.Find(p.ContentId);

            if (result.IsValid)
            {
                foreach (string item in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[item] as HttpPostedFileBase;
                    if (file.ContentLength == 0)
                        continue;
                    if (file.ContentLength > 0)
                    {
                        ImageUpload imageUpload = new ImageUpload { Width = 500 };
                        ImageResult imageResult = imageUpload.RenameUploadFile(file);

                        if (imageResult.Success)
                        {
                            p.Picture = imageResult.ImageName;
                        }
                        else
                        {
                            ViewBag.Error = imageResult.ErrorMessage;
                        }
                    }
                }

                value.Name = p.Name;
                value.Description = p.Description;
                value.IsActive = true;
                db.SaveChanges();
                TempData["AlertMessage"] = "İçerik Başarıyla Güncellendi";

                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult IsActive(int id)
        {
            var updatevalue = db.Contents.Find(id);
            if (updatevalue.IsActive == true)
            {
                updatevalue.IsActive = false;
            }
            else
            {
                updatevalue.IsActive = true;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteContent(int id)
        {
            var deletevalue = db.Contents.Find(id);
            deletevalue.IsActive = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcWeb/MvcWeb/Views/Content/AddContent.cshtml
@model MvcWeb.Models.Entity.Content

@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">İçerik</span> - Yönetimi</h4>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/Dashboard"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="/Content/Index/">İçerik Listesi</a></li>
            <li class="active">İçerik Ekle</li>
        </ul>
    </div>
</div>


<!-- Content area -->
<div class="content">
    <!-- /page header -->
    <div class="panel panel-flat">
        <div class="panel-body">
            @using (Html.BeginForm("AddContent", "Content", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-12">
                        <fieldset class="text-semibold">
                            <legend><i class="icon-reading position-left"></i> İçerik Başlık Bilgileri</legend>
                            <div class="form-group">
                                <label>Başlık Adı</label>
                                @Html.DropDownListFor(x => x.HeadingId, (List<SelectListItem>)ViewBag.value, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Başlık Adı</label>
                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Açıklama</label>
                                <textarea name="Description" class="ckeditor" id="editor-full" rows="4" cols="4"></textarea>
                            </div>
                            <div class="form-group">
                                <label>Görsel:</label>
                                <input type="file" name="Picture" id="UploadImage" class="form-control" />
                            </div>
                        </fieldset>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Kaydet <i class="icon-arrow-right14 position-right"></i></button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MvcWeb/MvcWeb/Views/Content/EditContent.cshtml
@model MvcWeb.Models.Entity.Content
@{
    ViewBag.Title = "EditContent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">İçerik</span> - Yönetimi</h4>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/Dashboard"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="/Content/Index">İçerik Listesi</a></li>
            <li><a href="/Content/AddContent">İçerik Ekle</a></li>
            <li class="active">İçerik Güncelle</li>
        </ul>
    </div>
</div>


<!-- Content area -->
<div class="content">
    <!-- /page header -->
    <div class="panel panel-flat">
        <div class="panel-body">
            @using (Html.BeginForm("EditContent", "Content", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(X => X.ContentId)
                <div class="row">
                    <div class="col-md-12">
                        <fieldset class="text-semibold">
                            <legend><i class="icon-reading position-left"></i> İçerik Başlık Bilgileri</legend>
                            <div class="form-group">
                                <label>Başlık Adı</label>
                                @Html.DropDownListFor(x => x.HeadingId, (List<SelectListItem>)ViewBag.value, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Başlık Adı</label>
                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <textarea name="Description" class="ckeditor" id="editor-full" rows="4" cols="4">@Model.Description</textarea>
                            </div>
                            <div class="form-group">
                                <label>Görsel:</label>
                                <input type="file" name="Picture" id="UploadImage" class="form-control" />
                                <br />
                                <img src="/Uploads/resize/@Model.Picture" width="350" />
                            </div>
                        </fieldset>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Kaydet <i class="icon-arrow-right14 position-right"></i></button>
                    </div>
                </div>

            }
        </div>
    </div>
</div>

MvcWeb/MvcWeb/Views/Content/Index.cshtml
@using MvcWeb.Models.Entity
@model List<Content>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">İçerik</span></h4>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/Dashboard"><i class="icon-home2 position-left"></i> Dashboard</a></li>
            <li><a href="/Content/AddContent">Yeni İçerik Ekle</a></li>
            <li class="active">İçerik Listesi</li>
        </ul>
    </div>
</div>
<!-- /page header -->
<!-- Content area -->
<div class="content">
    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">İçerik Başlığı</th>
                    <th scope="col">Bağlı Konum</th>
                    <th scope="col">Açıklama</th>
                    <th scope="col">Durum</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.ContentId</th>
                        <td>@item.Name</td>
                        <td>@item.Heading.Name</td>
                        <td>@Html.Raw(item.Description)</td>
                        <td>
                            @if (item.IsActive == true)
                            {
                                <a href="/Content/IsActive/@item.ContentId">
                                    <span class="bg-success text-highlight">Aktif</span>
                                </a>

                            }
                            else
                            {
                                <a href="/Content/IsActive/@item.ContentId">
                                    <span class="bg-danger text-highlight">Pasif</span>
                                </a>
                            }
                        </td>
                        <td>
                            <a href="/Content/EditContent/@item.ContentId" class="btn btn-warning">Güncelle</a>
                            <a href="/Content/DeleteContent/@item.ContentId" class="btn btn-danger">Sil</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>
<!-- /content area -->